### ISSUE TITLE
Incorrect comment parsing

### ISSUE THREAD

**Issue by cole-miller** [bodoni/svg#28]
Currently the following fragment

```xml
<!-- foo > -->
```

is incorrectly parsed as

```rust
Event::Comment, Event::Text("-->")
```

rather than the correct

```rust
Event::Comment
```

This happens because the following code allows `Comment`s to end with a simple `>` instead of requiring `-->`:

https://github.com/bodoni/svg/blob/f94579538c3808375dfa1cda5e371af74050d84e/src/parser/mod.rs#L72-L82

**Comment by IvanUkhov** [comment]
Thanks for reporting! Do you have time to review #29?

**Comment by cole-miller** [comment]
Sorry I didn't get the chance to look at the PR— thanks for fixing!
