### ISSUE TITLE
How to get the String out of svg::node::Value?

### ISSUE THREAD

**Issue by Geams** [bodoni/svg#30]
I am using the example "Parsing" from the crates.io page.
How can I get the String out of the tuple struct Value?
`let val = attributes.get("inkscape:groupmode");`
`if val.is_some(){`
`let val = val.unwrap();`
`let s = value.0; // ERROR: field `0` of struct `svg::node::value::Value` is private rustc(E0616)`
`} `

**Comment by IvanUkhov** [comment]
Hello, please give a try to either the `Into` or `Deref` trait.

**Comment by Geams** [comment]
Sorry, I am still a beginner at Rust.
I got the solution on stackoverflow
The deref trait did the trick:
`let s: &str = &*value;`
