### ISSUE TITLE
Method for accessing the element within a struct

### ISSUE THREAD

**Issue by mwbryant** [bodoni/svg#32]
I'm new to rust so pardon me if I'm misunderstanding anything.  It appears all the structs (Rectangle, etc) have an inner Element but this is private with no way for the user to access.  Element is public and has methods to access its inner workings but the structs are missing this. Is there a reason for this?

**Comment by IvanUkhov** [comment]
Hi, no worries! Well, it is not intended to be accessed. The inner struct is even hidden in the documentation:

https://github.com/bodoni/svg/blob/master/src/node/element/mod.rs#L15

What exactly should you like to read from there?

**Comment by mwbryant** [comment]
I am working on a library to make SVG animations and I want to be able to return the underlying element. My current workaround is wrapping elements inside a `SVG` to get this generality.

```rust
pub enum Mobject {
    Rectangle {...},
    Circle(...),
}


impl Mobject {
    pub fn to_addable(&self) -> element::SVG {
        match self {
            Mobject::Rectangle { ... } => element::SVG::new().add(
                element::Rectangle::new()
                    .set("x", *x)
                    .set("y", *y)
                    ...
            )
        }
    }
}

```

The other reason I would like access to the underlying element is for testing aspects of my animation library. For example, I would like to check `get_children` on these `SVG`s to make sure they are actually a `Rectangle` internally.  

Is there a better workaround or am I using this library incorrectly?

**Comment by IvanUkhov** [comment]
The inner element can actually be accessed using `get_inner`, which is undocumented:

https://github.com/bodoni/svg/blob/master/src/node/mod.rs#L96

I also don’t see why you need to wrap it in `element::SVG`. Use `element::Rectangle` directly.

**Comment by mwbryant** [comment]
Maybe I am thinking too object orientedly.  I can't just return Rectangle because that same function could also be called when Mobject was a circle.  That function could return any svg primitive or something more complex (like the axis for a graph).  Then when we render the goal was to be agnostic to the actual element types.

The `get_inner` function should solve the problem though.

**Comment by IvanUkhov** [comment]
I see. Yes, if one wants to return, one would have to find a common denominator, such as `Box<dyn Node>` or `Element` via `get_inner`.
