### ISSUE TITLE
Escape characters not working

### ISSUE THREAD

**Issue by Harri-Renney** [bodoni/svg#49]
Came across an issue where the parser does not match correctly when a "<" is included in an attribute value. This seems to be a problem with all these special characters. Using the expected alternative to escape the characters, such as "&lt;" has the same issue.

**Comment by IvanUkhov** [comment]
Can you please given an example that is according to the spec but not parsed correctly?

**Comment by IvanUkhov** [comment]
Should be solved by #52 when it comes to [entity](https://www.w3.org/TR/REC-xml/#NT-EntityRef) and [character](https://www.w3.org/TR/REC-xml/#NT-CharRef) references.
