### ISSUE TITLE
How to get large-arc-flag and sweep-flag from Parameters?

### ISSUE THREAD

**Issue by Mg138** [bodoni/svg#57]
How to get large-arc-flag and sweep-flag from Parameters? Does one simply cast from f32 to bool?
Would a helper method be possible, then? Or even a full page of methods for simple access with Parameters.
The library is nice, but this part seems particularly obscure.

**Comment by IvanUkhov** [comment]
Hi, `Parameters` is a vector of numbers. One could indeed take the one corresponding to the flag in question and cast.
