### ISSUE TITLE
Strict Type for `set(name, value)` 

### ISSUE THREAD

**Issue by lameferret** [bodoni/svg#58]
## Problem
Currently, `set()`  can take any valid string as input, which isn't desirable(?). 

**Note**: Considering the number of elements there are, it's kind of understandable to have lax methods.

**Question**: What's the current reasoning for not having type safety, other than a lot of repetition and not as elegant macro implementation?

## Possible Solution
Adding `set_strict()` which takes `(name: enum, value: T)`, passes `(name.to_string(), value)` to `set()` internally.

Value can have type safety too, but I don't think I can do that without `serde` specifically for hexadecimal colour.

### Dealing with breaking change
- Minor release: `set()` can be exposed as it is, while having `set_strict()` as another option.
- Major release: `set()` can be renamed to `set_raw()` and `set_strict()` replaces `set()`. Giving both options of customizability and type safety.

_**If I can get some direction and tips as I don't know much about `svg` I would love to work on this.**_

**Comment by IvanUkhov** [comment]
Hello, could you please explain a bit more? `set` does not only take strings but other `Value`s too. Or do you mean you want to impose specific types for specific attributes?

**Comment by lameferret** [comment]
Sorry @IvanUkhov, for not being able to express the suggestion clearly.

#### Current usage
```rust
let rect = Rectangle::new()
        .set("x", 0)
        .set("y", 0)
        .set("width", 200)
        .set("height", 100)
        .set("fill", "#ffffff");
```
Works fine, but gets complicated with multiple elements, and prone to all the issues type safety solves.

#### Suggestion
```rust
enum StrictAttributes {
    X(usize),
    Y(usize),
    Width(usize),
    ...
    Fill(String) // Could be a HexColor type
}

impl Rectangle {
... // Rest of the functions
    pub fn strict_set(mut self, input: StrictAttributes) {
        match input {
            X(input) => Self::set("x", input),
            Y(input) => Self::set("y", input),
            ...
            Fill(input) => Self::set("fill", input)
        }
}
```

Right now, `macros` are being used to implement almost all the functions, made possible by `Into<String>` and `Into<node::Value>` types for `name` and `value` respectively. 

The only way I can think of adding type safety is adding a lot of repetitive code with enums for each element with its specific attribute and implementing `new_set()` function for it.

Could avoid some repetition with hacky way to extend and combine traits, but that would make API real ugly.
```rust
enum GeometryAttributes {
    X(usize),
    ...,
    RY(usize)
}

enum FillAttributes {
    Fill(Color),
    FillRule(),
    ...
}
enum RectangleElement {
    GeometryAttributes(GeometryAttributes),
    FillAttributes(FillAttributes)
    ... 
}
```


What do you think, will this make crate experience better, or would be too big of a change to deal with?

**Comment by IvanUkhov** [comment]
So this is indeed about enforcing specific types for specific attributes for specific tags, right? For instance, `x` of `Rectangle` should be an integer but could be accidentally assigned, say, a string.

I am not sure how one would go about it in a scalable and error-free way. There are many tags, and each one has many attributes with their respective types. Indeed, one would have to maintain some kind of a mapping of which tags support which attributes. Each tag would have to be hand-crafted. Or do you see it differently?

The simplicity of the crate is due to it treating pretty much all tags identically.

**Comment by lameferret** [comment]
> So this is indeed about enforcing specific types for specific attributes for specific tags, right? For instance, x of Rectangle should be an integer but could be accidentally assigned, say, a string.
Yes, that's what I meant.

> Each tag would have to be hand-crafted. Or do you see it differently?
No, I don't have any workaround.

I think, I should close the issue as enforcing strict type is great but here it would come with more demerits of extra code to maintain. 

Anyway, thanks for your time.
