### ISSUE TITLE
How do I get their nested relationship from the parsing, because some properties might be in the parent like g

### ISSUE THREAD

**Issue by tetap** [bodoni/svg#65]
![image](https://user-images.githubusercontent.com/57606461/217543327-4911fb43-0089-48bc-bc46-3e34e6f5afcc.png)

**Comment by IvanUkhov** [comment]
Hello, the library does not currently keep track of this. It simply exposes the content in the order it appears.

**Comment by tetap** [comment]
> Hello, the library does not currently keep track of this. It simply exposes the content in the order it appears.

OK, thank you！
