### ISSUE TITLE
Publish new version on crates.io

### ISSUE THREAD

**Issue by s0l0ist** [bodoni/svg#75]
Hello, 

Can you publish a new patch release of this library on crates.io? I would love to remove the dependence on my private fork since these changes were merged upstream: https://github.com/bodoni/svg/commit/d272e7689c76487a3bce3d656fe6bfccba2e449a

Many thanks in advance!

**Comment by IvanUkhov** [comment]
Hello, it was published as part of 0.14.

**Comment by s0l0ist** [comment]
I see, thanks!
