### ISSUE TITLE
`<` in Text nodes is not escaped

### ISSUE THREAD

**Issue by konstin** [bodoni/svg#76]
I'm using [this code](https://github.com/konstin/tracing-durations-export/blob/84eec129689b227a67aec91d26dfb23ccee64383/src/plot.rs#L287-L308) to add tooltips to boxes. If the string contents e.g. contains `widgets >=3.0.9, <3.1.dev0`, the `<` is not escaped and produces and invalid svg:

```svg
<rect fill="#FF780088" height="10" width="0.3088995" x="328.0725" y="120">
<title>
widgets >=3.0.9, <3.1.dev0
</title>
</rect>
```

**Comment by IvanUkhov** [comment]
Thank you! I have updated the logic to do the escaping:

https://github.com/bodoni/svg/blob/main/src/node/element/mod.rs#L436-L455

**Comment by konstin** [comment]
Thanks!
