### ISSUE TITLE
Question: How do you assign the text content for a `element::Text` node?

### ISSUE THREAD

**Issue by sunkit02** [bodoni/svg#77]
I have been exploring the library and found most things quite intuitive, but I can't seem to figure out how to assign the text content for a `Text` node after creating it with the following code:
```rust
use svg::node::element::Text;

let text = Text::new();
```

The target behavior is to generate a `<text>` tag containing a string that I provide through the rust program like the following:
```
<text>Hello, world</text>
```

Thank you so much for your help!

**Comment by IvanUkhov** [comment]
Yes, it has come up multiple times, and it is the most confusing part, unfortunately. Please take a look at this example (so `node::Text` should be attached as a child to `node::element::Text`):

https://github.com/bodoni/svg/blob/main/src/node/element/mod.rs#L436-L455

**Comment by sunkit02** [comment]
Problem solved, thank you so much!
