### ISSUE TITLE
How do I add text to a document?

### ISSUE THREAD

**Issue by saethlin** [bodoni/svg#8]
As far as I can tell, I can't use `svg::node::Text` because its `Node` implementation is stubbed out, and I can't use `svg::node::element::Text` because there's no way to set the actual text of the element.

If you just haven't gotten around to making text work yet, I'm happy to do that.
I really want it.

**Comment by IvanUkhov** [comment]
Thanks for the issue! Please help me understand what the problem is. The implementation of `Node` for `svg::node::Text` is how it should be since text nodes have no children or attributes. The content of a text node can be set upon construction, namely by passing a certain text to `Text::new`.

**Comment by saethlin** [comment]
[It looks to me like text elements have attributes.](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text)

But more importantly, I'm trying to create an element that looks like this
```
<text x="57.5" y="15" fill="#010101" fill-opacity=".3">failing</text>
````
How can I do this with your library?

**Comment by IvanUkhov** [comment]
We’re talking about two different aspects. There are text nodes, and there are text elements (text element nodes). I was referring to the former, and you to the latter.

I think you can try to do something along the following lines:

```rust
let text = node::element::Text::new().add(node::Text::new("failing"));
```

**Comment by paulkernfeld** [comment]
Hi there! I'm also a bit confused about this. How can I use the `svg` crate to generate the following snippet from the [MDN SVG documentation](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text)?

```xml
<text x="20" y="35" class="small">My</text>
```

**Comment by paulkernfeld** [comment]
Ah, I just figured it out. To add text, you need a `svg::node::Text` inside of a `svg::node::element::Text`:

```rust
svg::node::element::Text::new()
    .set("x", 20)
    .set("y", 35)
    .set("class", "small")
    .add(
        svg::node::Text::new("My")
    )
```

**Comment by wez** [comment]
I feel like this would be a great example for the docs!
