### ISSUE TITLE
Remove newlines around node::Text?

### ISSUE THREAD

**Issue by auberisky** [bodoni/svg#80]
Hi,

there should probably be no newlines around text nodes, as white space content of elements can be meaningful.

The newlines in titles like [here](https://github.com/bodoni/svg/blob/main/src/node/element/mod.rs#L436-L455) could even render as `⤶` in some situations.

Thanks,
Auberi

**Comment by IvanUkhov** [comment]
Thank you! Fixed. Added also shortcuts for Text, Title, and TSpan.

**Comment by auberisky** [comment]
Awesome! Thank you!
