### ISSUE TITLE
The <textPath> element cannot set inner text

### ISSUE THREAD

**Issue by hubenchang0515** [bodoni/svg#82]
The `<textPath>` element cannot set inner text
```rust
let text_path = TextPath::new();    // TextPath does not have arg to set text
let text = Text::new("xxxx");       // But Text does
```
the `<textPath>` should look like [this](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/textPath): 
```xml
<text>
    <textPath href="#MyPath">Quick brown fox jumps over the lazy dog.</textPath>
</text>
```

**Comment by IvanUkhov** [comment]
You see the text is a node nested in `textPath`; it is not an attribute. So you need to append it to your `test_path`. However, we provide an argument to `new` in such cases, and this one was missed. Fixed. Please try with `TextPath::new("Quick brown fox jumps over the lazy dog.")`.
