### ISSUE TITLE
How to define patterns?

### ISSUE THREAD

**Issue by e-matteson** [bodoni/svg#9]
I want to define a [pattern element](https://www.w3.org/TR/SVG/pservers.html#PatternElement), and don't see a struct for that. Is there currently any way to work with patterns? Or is adding support for them as simple as adding it to the list of elements created with`implement!`? If so, I can submit a pull request.

**Comment by IvanUkhov** [comment]
Thanks for the issue! Yes, please feel free to open a pull request. Yes, it should be straightforward to extend. There are two `implement!` that should be updated (see `mod.rs` and `tag.rs`); please keep them sorted alphabetically.
